### ISSUE TITLE
Question - Aspect-Slope raster function

### ISSUE THREAD

**Issue by mytototo** [frontiersi/mapbox-gl-esri-sources#10]
Hey!

Using this library, how can we leverage the [Aspect-Slope raster function from Esri](https://pro.arcgis.com/en/pro-app/latest/help/analysis/raster-functions/aspect-slope-function.htm) in Mapbox?

I didn't find any docs or examples about it.

Thank you.

**Comment by rowanwins** [comment]
Hi @mytototo 

Concievably you could achieve something.

Basically you need to pass a custom `renderingRule` [parameter](https://developers.arcgis.com/documentation/common-data-types/raster-function-objects.htm) to an [ImageService](https://developers.arcgis.com/rest/services-reference/enterprise/export-image.htm).

Looking at the doco above for the ArcGIS Rest API there pre-canned renderings for Aspect, and Slope, but not the combined Aspect-Slope analysis that's available in ArcPro, I'm not sure why that is or how hard it would be to replicate.

Here's some ideas for how to use the `renderingRule` parameter though
````
import {ImageService} from 'mapbox-gl-esri-sources'
          
const aspectImageService = new ImageService('aspect-source', map, {
    url: 'https://sampleserver6.arcgisonline.com/arcgis/rest/services/NLCDLandCover2001/ImageServer',
   renderingRule: {
      "rasterFunction": "Aspect"
   }
})

const slopeImageService = new ImageService('slope-source', map, {
    url: 'https://sampleserver6.arcgisonline.com/arcgis/rest/services/NLCDLandCover2001/ImageServer',
   renderingRule: {
      "rasterFunction": "Slope",
      "rasterFunctionArguments": {
         "ZFactor": 0.3
       }
    }
})

````

**Comment by mytototo** [comment]
Awesome, thank you very much for your help! It works just like you mentioned.
