### ISSUE TITLE
Identify features from a Dynamic Map Service are shown when layer is not visible

### ISSUE THREAD

**Issue by PedroVenancio** [frontiersi/mapbox-gl-esri-sources#4]
Hi,

I'm trying the Identify features from a Dynamic Map Service, and the identify output is shown even when the layer is disabled by the maplibre-gl-legend module. Here is a sample:

https://codepen.io/PedroNGV/pen/PoBWNpM

![imagem](https://user-images.githubusercontent.com/1331581/211167612-a9a962f6-59d4-49cc-8ba1-1120dad63d68.png)

The expected behaviour would be the popup not be shown when the layer is disabled, like in the default popup (https://maplibre.org/maplibre-gl-js-docs/example/popup-on-click/).

Do you think this is a bug? Or just a misconfiguration?

Thanks!

**Comment by rowanwins** [comment]
So maplibre-gl-legend works by toggling the `visibility` layout of an layer.

So you could do something like
````
      map.on('click', function(e) {
        if (map.getLayoutProperty('dynamic_source', 'visibility') === 'none') return
        ...
````

There are reasons why you might want to run an identify even if the layer wasn't shown, so I think it's best for you to incorporate something like the above into your code.

Hope that helps :)

**Comment by PedroVenancio** [comment]
Hi @rowanwins 

> So you could do something like
> 
> ```
>       map.on('click', function(e) {
>         if (map.getLayoutProperty('dynamic_source', 'visibility') === 'none') return
>         ...
> ```

Thank you very much! It works like a charm! 
 
> There are reasons why you might want to run an identify even if the layer wasn't shown, so I think it's best for you to incorporate something like the above into your code.

I agree, it's better this way.

Thanks @rowanwins !
