### ISSUE TITLE
Identify requests does not work when layer default visibility is false

### ISSUE THREAD

**Issue by PedroVenancio** [frontiersi/mapbox-gl-esri-sources#5]
Hi @rowanwins 

The identify request does not work when the queried layer has default visibility property as false (`"defaultVisibility": false`). 

In this sample https://codepen.io/PedroNGV/pen/wvxgmOp :

- `Elevation` layer returns the identify output as expected;
- `Slope` layer does not return nothing.

The diference between both layers is:
- `Elevation` has Default Visibility: true;
- `Slope` has Default Visibility: false.

Looking at the request:
`https://sigservices.icnf.pt/server/rest/services/BDG/LF_PT_RELEVO/MapServer/identify?sr=4326&geometryType=esriGeometryPoint&geometry=%7B%22x%22%3A-7.065627735444195%2C%22y%22%3A40.77396674193105%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&tolerance=3&returnGeometry=false&imageDisplay=1920%2C553%2C96&mapExtent=-7.082986992188637%2C40.77110672954365%2C-7.050028007813523%2C40.77830527567522&layers=show%3A14&layerDefs=false&time=false&f=json`

I see `layers=show:14`

which came from
https://github.com/frontiersi/mapbox-gl-esri-sources/blob/master/src/DynamicMapService.js#L42
and
https://github.com/frontiersi/mapbox-gl-esri-sources/blob/master/src/DynamicMapService.js#L156

I've checked how esri-leaflet deal with identify requests, and it seems to use `visible:` (`layers=visible:14`) instead of `show:`
https://github.com/Esri/esri-leaflet/blob/daebcc8f69930a90b4ec726b0eb34fbe393d90af/src/Layers/DynamicMapLayer.js#L100

Changing https://github.com/frontiersi/mapbox-gl-esri-sources/blob/master/src/DynamicMapService.js#L156 to use `visible:`, the output already came as expected, both in Elevation and Slope layers.

Do you think this change should be applied?

Thanks!

**Comment by rowanwins** [comment]
Hi @PedroVenancio ,

Yep, good diagnosis, it appears the query parameters required for the `identify` endpoint are

````
layers=visible:14
// RATHER THAN 
layers=show:14
````
See Esri doco [here](https://sigservices.icnf.pt/server/sdk/rest/index.html#/Identify_Map_Service/02ss000000m7000000/)

This requires a slight modification in the [codebase here](https://github.com/frontiersi/mapbox-gl-esri-sources/blob/master/src/DynamicMapService.js#L156) if you'd like to support a PR :)

Cheers

**Comment by PedroVenancio** [comment]
Hi @rowanwins 

This simple workaround solves the issue:
https://github.com/frontiersi/mapbox-gl-esri-sources/blob/master/src/DynamicMapService.js#L156
to
`layers: this._layersStr.replace("show", "visible"),`

but I believe it can be done in a better way.

**Comment by rowanwins** [comment]
Resolved in v0.0.5 which has just been published.

**Comment by PedroVenancio** [comment]
Perfect! Thank you very much @rowanwins !
