### ISSUE TITLE
Docs out of date for ImageMapService should be ImageService

### ISSUE THREAD

**Issue by yuletide** [frontiersi/mapbox-gl-esri-sources#9]
Following the docs results in:
Error: mapbox_gl_esri_sources__WEBPACK_IMPORTED_MODULE_4__.ImageMapService is not a constructor
    at mapbox-gl.js:31:1

Edit: I see the docs are out of date, should be `ImageService` https://github.com/frontiersi/mapbox-gl-esri-sources/blob/master/src/main.js

https://github.com/frontiersi/mapbox-gl-esri-sources/blob/master/docs/src/pages/examples/ImageServiceBasic.vue#L10

**Comment by rowanwins** [comment]
Thanks for flagging @yuletide - now fixed in the docs
